import { LibraryExercise, ExerciseSet } from '../types';

// Omit 'id' because it will be generated by Firestore
type DefaultExercise = Omit<LibraryExercise, 'id'>;

const createSets = (count: number, type: 'reps_load' | 'reps_time', reps: string, load: string = '', time: string = ''): ExerciseSet[] => {
    const sets: ExerciseSet[] = [];
    for (let i = 0; i < count; i++) {
        sets.push({
            id: `set-${i + 1}-${Math.random()}`,
            type: type,
            reps: reps,
            load: load,
            time: time,
        });
    }
    return sets;
};


export const defaultExercises: DefaultExercise[] = [
  // Peito
  { name: 'Supino Reto (Barra)', category: 'Musculação', muscleGroup: 'Peito', rest: '60s', sets: createSets(3, 'reps_load', '8-12', 'Ajustar'), youtubeUrl: '' },
  { name: 'Supino Inclinado (Halteres)', category: 'Musculação', muscleGroup: 'Peito', rest: '60s', sets: createSets(3, 'reps_load', '8-12', 'Ajustar'), youtubeUrl: '' },
  { name: 'Crucifixo (Halteres)', category: 'Musculação', muscleGroup: 'Peito', rest: '60s', sets: createSets(3, 'reps_load', '12-15', 'Ajustar'), youtubeUrl: '' },
  { name: 'Flexão de Braço', category: 'Musculação', muscleGroup: 'Peito', rest: '60s', sets: createSets(3, 'reps_load', 'Até a falha'), youtubeUrl: '' },
  { name: 'Voador (Peck Deck)', category: 'Musculação', muscleGroup: 'Peito', rest: '60s', sets: createSets(3, 'reps_load', '12-15', 'Ajustar'), youtubeUrl: '' },

  // Costas
  { name: 'Puxada Frontal (Pulley)', category: 'Musculação', muscleGroup: 'Costas', rest: '60s', sets: createSets(3, 'reps_load', '8-12', 'Ajustar'), youtubeUrl: '' },
  { name: 'Remada Curvada (Barra)', category: 'Musculação', muscleGroup: 'Costas', rest: '60s', sets: createSets(3, 'reps_load', '8-12', 'Ajustar'), youtubeUrl: '' },
  { name: 'Remada Cavalinho', category: 'Musculação', muscleGroup: 'Costas', rest: '60s', sets: createSets(3, 'reps_load', '10-15', 'Ajustar'), youtubeUrl: '' },
  { name: 'Barra Fixa', category: 'Musculação', muscleGroup: 'Costas', rest: '60s', sets: createSets(3, 'reps_load', 'Até a falha'), youtubeUrl: '' },
  { name: 'Serrote (Remada Unilateral)', category: 'Musculação', muscleGroup: 'Costas', rest: '60s', sets: createSets(3, 'reps_load', '10-12', 'Ajustar'), youtubeUrl: '' },

  // Pernas
  { name: 'Agachamento Livre', category: 'Musculação', muscleGroup: 'Pernas', rest: '90s', sets: [
      { id: 's1', type: 'reps_load', reps: '15', load: 'Aquecimento' },
      { id: 's2', type: 'reps_load', reps: '12', load: 'Ajustar' },
      { id: 's3', type: 'reps_load', reps: '10', load: 'Ajustar' },
      { id: 's4', type: 'reps_load', reps: '8', load: 'Ajustar' },
  ], youtubeUrl: '' },
  { name: 'Leg Press 45', category: 'Musculação', muscleGroup: 'Pernas', rest: '90s', sets: createSets(4, 'reps_load', '10-15', 'Ajustar'), youtubeUrl: '' },
  { name: 'Cadeira Extensora', category: 'Musculação', muscleGroup: 'Pernas', rest: '60s', sets: createSets(3, 'reps_load', '12-15', 'Ajustar'), youtubeUrl: '' },
  { name: 'Mesa Flexora', category: 'Musculação', muscleGroup: 'Pernas', rest: '60s', sets: createSets(3, 'reps_load', '12-15', 'Ajustar'), youtubeUrl: '' },
  { name: 'Afundo (Passada)', category: 'Musculação', muscleGroup: 'Pernas', rest: '60s', sets: createSets(3, 'reps_load', '10-12 p/ perna', 'Ajustar'), youtubeUrl: '' },
  { name: 'Stiff', category: 'Musculação', muscleGroup: 'Pernas', rest: '90s', sets: createSets(3, 'reps_load', '10-12', 'Ajustar'), youtubeUrl: '' },
  { name: 'Elevação Pélvica', category: 'Musculação', muscleGroup: 'Pernas', rest: '60s', sets: createSets(3, 'reps_load', '15-20', 'Ajustar'), youtubeUrl: '' },
  { name: 'Panturrilha em Pé', category: 'Musculação', muscleGroup: 'Pernas', rest: '45s', sets: createSets(4, 'reps_load', '15-20', 'Ajustar'), youtubeUrl: '' },

  // Ombros
  { name: 'Desenvolvimento Militar (Barra)', category: 'Musculação', muscleGroup: 'Ombros', rest: '75s', sets: createSets(3, 'reps_load', '8-12', 'Ajustar'), youtubeUrl: '' },
  { name: 'Elevação Lateral (Halteres)', category: 'Musculação', muscleGroup: 'Ombros', rest: '60s', sets: createSets(3, 'reps_load', '12-15', 'Ajustar'), youtubeUrl: '' },
  { name: 'Elevação Frontal', category: 'Musculação', muscleGroup: 'Ombros', rest: '60s', sets: createSets(3, 'reps_load', '12-15', 'Ajustar'), youtubeUrl: '' },
  { name: 'Remada Alta', category: 'Musculação', muscleGroup: 'Ombros', rest: '60s', sets: createSets(3, 'reps_load', '10-15', 'Ajustar'), youtubeUrl: '' },

  // Bíceps
  { name: 'Rosca Direta (Barra)', category: 'Musculação', muscleGroup: 'Bíceps', rest: '60s', sets: createSets(3, 'reps_load', '8-12', 'Ajustar'), youtubeUrl: '' },
  { name: 'Rosca Alternada (Halteres)', category: 'Musculação', muscleGroup: 'Bíceps', rest: '60s', sets: createSets(3, 'reps_load', '10-12 p/ braço', 'Ajustar'), youtubeUrl: '' },
  { name: 'Rosca Martelo', category: 'Musculação', muscleGroup: 'Bíceps', rest: '60s', sets: createSets(3, 'reps_load', '10-12 p/ braço', 'Ajustar'), youtubeUrl: '' },

  // Tríceps
  { name: 'Tríceps Pulley (Corda)', category: 'Musculação', muscleGroup: 'Tríceps', rest: '60s', sets: createSets(3, 'reps_load', '10-15', 'Ajustar'), youtubeUrl: '' },
  { name: 'Tríceps Testa', category: 'Musculação', muscleGroup: 'Tríceps', rest: '60s', sets: createSets(3, 'reps_load', '8-12', 'Ajustar'), youtubeUrl: '' },
  { name: 'Mergulho no Banco', category: 'Musculação', muscleGroup: 'Tríceps', rest: '60s', sets: createSets(3, 'reps_load', 'Até a falha'), youtubeUrl: '' },

  // Abdômen
  { name: 'Abdominal Supra', category: 'Musculação', muscleGroup: 'Abdômen', rest: '45s', sets: createSets(3, 'reps_load', '15-20'), youtubeUrl: '' },
  { name: 'Prancha Isométrica', category: 'Musculação', muscleGroup: 'Abdômen', rest: '45s', sets: createSets(3, 'reps_time', '', '', '30-60s'), youtubeUrl: '' },
  { name: 'Elevação de Pernas (Infra)', category: 'Musculação', muscleGroup: 'Abdômen', rest: '45s', sets: createSets(3, 'reps_load', '15-20'), youtubeUrl: '' },

  // Cardio
  { name: 'Esteira', category: 'Cardio', muscleGroup: 'Corpo Inteiro', rest: 'N/A', sets: [{ id: 'c1', type: 'run', time: '20 min', distance: 'Moderado' }], youtubeUrl: '' },
  { name: 'Bicicleta Ergométrica', category: 'Cardio', muscleGroup: 'Corpo Inteiro', rest: 'N/A', sets: [{ id: 'c2', type: 'run', time: '20 min', distance: 'Moderado' }], youtubeUrl: '' },
  { name: 'Elíptico (Transport)', category: 'Cardio', muscleGroup: 'Corpo Inteiro', rest: 'N/A', sets: [{ id: 'c3', type: 'run', time: '15 min', distance: 'Moderado' }], youtubeUrl: '' },
  { name: 'Pular Corda', category: 'Cardio', muscleGroup: 'Corpo Inteiro', rest: 'N/A', sets: [{ id: 'c4', type: 'reps_time', reps: '5 rounds', time: '1 min ativo, 30s descanso' }], youtubeUrl: '' },

  // Funcional
  { name: 'Burpee', category: 'Funcional', muscleGroup: 'Corpo Inteiro', rest: '60s', sets: createSets(4, 'reps_load', '10-15'), youtubeUrl: '' },
  { name: 'Kettlebell Swing', category: 'Funcional', muscleGroup: 'Corpo Inteiro', rest: '60s', sets: createSets(3, 'reps_load', '15-20', 'Ajustar'), youtubeUrl: '' },
  { name: 'Agachamento com Salto', category: 'Funcional', muscleGroup: 'Pernas', rest: '60s', sets: createSets(3, 'reps_load', '15-20'), youtubeUrl: '' },

  // Alongamento
  { name: 'Alongamento de Posteriores', category: 'Alongamento', muscleGroup: 'Pernas', rest: 'N/A', sets: [{ id: 'a1', type: 'observation', observation: 'Segurar por 30 segundos em cada perna.' }], youtubeUrl: '' },
  { name: 'Alongamento de Quadríceps', category: 'Alongamento', muscleGroup: 'Pernas', rest: 'N/A', sets: [{ id: 'a2', type: 'observation', observation: 'Segurar por 30 segundos em cada perna.' }], youtubeUrl: '' },
  { name: 'Alongamento de Peitoral', category: 'Alongamento', muscleGroup: 'Peito', rest: 'N/A', sets: [{ id: 'a3', type: 'observation', observation: 'Segurar por 30 segundos.' }], youtubeUrl: '' },
];