import { LibraryExercise } from '../types';

// Omit 'id' because it will be generated by Firestore
type DefaultExercise = Omit<LibraryExercise, 'id'>;

export const defaultExercises: DefaultExercise[] = [
  // Peito
  { name: 'Supino Reto (Barra)', category: 'Musculação', muscleGroup: 'Peito', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Supino Inclinado (Halteres)', category: 'Musculação', muscleGroup: 'Peito', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Crucifixo (Halteres)', category: 'Musculação', muscleGroup: 'Peito', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Flexão de Braço', category: 'Musculação', muscleGroup: 'Peito', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Voador (Peck Deck)', category: 'Musculação', muscleGroup: 'Peito', rest: '60s', sets: [], youtubeUrl: '' },

  // Costas
  { name: 'Puxada Frontal (Pulley)', category: 'Musculação', muscleGroup: 'Costas', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Remada Curvada (Barra)', category: 'Musculação', muscleGroup: 'Costas', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Remada Cavalinho', category: 'Musculação', muscleGroup: 'Costas', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Barra Fixa', category: 'Musculação', muscleGroup: 'Costas', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Serrote (Remada Unilateral)', category: 'Musculação', muscleGroup: 'Costas', rest: '60s', sets: [], youtubeUrl: '' },

  // Pernas
  { name: 'Agachamento Livre', category: 'Musculação', muscleGroup: 'Pernas', rest: '90s', sets: [], youtubeUrl: '' },
  { name: 'Leg Press 45', category: 'Musculação', muscleGroup: 'Pernas', rest: '90s', sets: [], youtubeUrl: '' },
  { name: 'Cadeira Extensora', category: 'Musculação', muscleGroup: 'Pernas', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Mesa Flexora', category: 'Musculação', muscleGroup: 'Pernas', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Afundo (Passada)', category: 'Musculação', muscleGroup: 'Pernas', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Stiff', category: 'Musculação', muscleGroup: 'Pernas', rest: '90s', sets: [], youtubeUrl: '' },
  { name: 'Elevação Pélvica', category: 'Musculação', muscleGroup: 'Pernas', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Panturrilha em Pé', category: 'Musculação', muscleGroup: 'Pernas', rest: '45s', sets: [], youtubeUrl: '' },

  // Ombros
  { name: 'Desenvolvimento Militar (Barra)', category: 'Musculação', muscleGroup: 'Ombros', rest: '75s', sets: [], youtubeUrl: '' },
  { name: 'Elevação Lateral (Halteres)', category: 'Musculação', muscleGroup: 'Ombros', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Elevação Frontal', category: 'Musculação', muscleGroup: 'Ombros', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Remada Alta', category: 'Musculação', muscleGroup: 'Ombros', rest: '60s', sets: [], youtubeUrl: '' },

  // Bíceps
  { name: 'Rosca Direta (Barra)', category: 'Musculação', muscleGroup: 'Bíceps', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Rosca Alternada (Halteres)', category: 'Musculação', muscleGroup: 'Bíceps', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Rosca Martelo', category: 'Musculação', muscleGroup: 'Bíceps', rest: '60s', sets: [], youtubeUrl: '' },

  // Tríceps
  { name: 'Tríceps Pulley (Corda)', category: 'Musculação', muscleGroup: 'Tríceps', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Tríceps Testa', category: 'Musculação', muscleGroup: 'Tríceps', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Mergulho no Banco', category: 'Musculação', muscleGroup: 'Tríceps', rest: '60s', sets: [], youtubeUrl: '' },

  // Abdômen
  { name: 'Abdominal Supra', category: 'Musculação', muscleGroup: 'Abdômen', rest: '45s', sets: [], youtubeUrl: '' },
  { name: 'Prancha Isométrica', category: 'Musculação', muscleGroup: 'Abdômen', rest: '45s', sets: [], youtubeUrl: '' },
  { name: 'Elevação de Pernas (Infra)', category: 'Musculação', muscleGroup: 'Abdômen', rest: '45s', sets: [], youtubeUrl: '' },

  // Cardio
  { name: 'Esteira', category: 'Cardio', muscleGroup: 'Corpo Inteiro', rest: 'N/A', sets: [], youtubeUrl: '' },
  { name: 'Bicicleta Ergométrica', category: 'Cardio', muscleGroup: 'Corpo Inteiro', rest: 'N/A', sets: [], youtubeUrl: '' },
  { name: 'Elíptico (Transport)', category: 'Cardio', muscleGroup: 'Corpo Inteiro', rest: 'N/A', sets: [], youtubeUrl: '' },
  { name: 'Pular Corda', category: 'Cardio', muscleGroup: 'Corpo Inteiro', rest: 'N/A', sets: [], youtubeUrl: '' },

  // Funcional
  { name: 'Burpee', category: 'Funcional', muscleGroup: 'Corpo Inteiro', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Kettlebell Swing', category: 'Funcional', muscleGroup: 'Corpo Inteiro', rest: '60s', sets: [], youtubeUrl: '' },
  { name: 'Agachamento com Salto', category: 'Funcional', muscleGroup: 'Pernas', rest: '60s', sets: [], youtubeUrl: '' },

  // Alongamento
  { name: 'Alongamento de Posteriores', category: 'Alongamento', muscleGroup: 'Pernas', rest: 'N/A', sets: [], youtubeUrl: '' },
  { name: 'Alongamento de Quadríceps', category: 'Alongamento', muscleGroup: 'Pernas', rest: 'N/A', sets: [], youtubeUrl: '' },
  { name: 'Alongamento de Peitoral', category: 'Alongamento', muscleGroup: 'Peito', rest: 'N/A', sets: [], youtubeUrl: '' },
];
